name: Build and test
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SF_BUILD_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SF_BUILD_USERNAME }} --setdefaultdevhubusername --instanceurl ${{ secrets.SF_BUILD_URL }}
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Validate and run tests
      run: node_modules/sfdx-cli/bin/run force:source:deploy --targetusername ${{ secrets.SF_BUILD_USERNAME }} --sourcepath dev-app-pre,force-app,dev-app-post --testlevel RunAllTestsInOrg --checkonly --ignorewarnings